### ISSUE TITLE
Feedback on hw3

### ISSUE THREAD

**Issue by troyshu** [cuny-sps-msda-data622-2017fall/data622hw3#1]
Overall, looks good!

I felt a little unclear about "Design 2 different ways of migrating homework 2's outputs to AWS/GCP". My first question was: what are the goals of this question? Is it to get students familiar with the "ship intermediate output" step in the Agile Data Science Manifesto (slide 15 at https://www.slideshare.net/rjurney/agile-data-science-20, I don't have the book unfortunately...)? And/or the process of building systems for iterative (or "Agile") data science? Is it to test their understanding of the various systems of AWS/GCP (e.g. EC2, RDS, S3, etc.)?

Either way, I think providing some context around the goal(s) for this question can help guide students into figuring out what the original question is trying to get at, and how they can best answer it.

**Comment by sunwsusan** [comment]
Understood!  I will focus on this during the lecture (slide 11 on https://docs.google.com/presentation/d/1nfE-7tewF1gMXSCw5f5-zr8aqBjg5M-lwzEhgJUeUQE/).  The intent here is to have students do research on the breadth of tools available to them in GCP and AWS instead of my dictating which tools to use.  Also, this will require students to go back and do the assigned reading from hw2.  

Feel free to borrow my book if you like.
